# -*- coding: utf-8 -*-
"""LinearRegression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ayr-Tw4yrQi9j1Ck5D21Em3qeKoNcUBP
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

num_features = 4
num_targets = 1
df = pd.read_csv("/content/QSTP_LinReg.csv")

y = df['PE'].values
X = df.drop(['PE'],axis=1).values

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=0)

regressor = LinearRegression(fit_intercept=True)
model = regressor.fit(train_X,train_y)
prediction = model.predict(test_X)

r2_score(test_y,prediction)