# -*- coding: utf-8 -*-
"""LogisticRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aprglt-i5GBz3zYrAiZVhm6d3XDU2GLB
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv("/content/QSTP_LogReg.csv")

y = df['Class'].values
X = df.drop(['Class','Sample code number'],axis=1).values

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=0)

classifier = LogisticRegression()
model = classifier.fit(train_X,train_y)
prediction = model.predict(test_X)

accuracy_score(test_y, prediction)

confusion_matrix(test_y, prediction)